server:
  port: 8000
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenlinh.devv@gmail.com
    password: rjzk tvjl yxzd ueoq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
app:
  jwt:
    issuer: from server
    # Hỗ trợ định dạng ISO-8601 duration: PT15M (15 phút), P30D (30 ngày)
    access-token-expiration: P30D
    refresh-token-expiration: P30D
    secret: ${JWT_SECRET:Vt1yQZ4mK8rN2sP6xD9fA3cH7jL0wT5yU8iR2oE6bG9nC3vM7pQ1sL4dF8hJ2kR}
  cors:
    allowed-origins: http://localhost:3000
  cron:
    mail:
      enabled: true
      # Cron 6 trường: giây phút giờ ngày-tháng tháng thứ. Có thể thay bằng biểu thức chuẩn, ví dụ: "0 0 9 * * *" (9h mỗi ngày)
      # Mặc định: 30 giây/lần
      expression: 0/30 * * * * *
      # Số job gửi tối đa trong email
      top-jobs-limit: 5
  web:
    # Base URL FE để dựng link chi tiết job
    base-url: http://localhost:3000
    # Mẫu path chi tiết job, {id} sẽ được thay bằng job id
    job-detail-path: /job/{id}
  seed:
    enabled: false
  admin:
    email: ${ADMIN_EMAIL:admin@gmail.com}
    password: ${ADMIN_PASSWORD:123456}
    name: ${ADMIN_NAME:Admin}
    address: ${ADMIN_ADDRESS:Hà Nội}
    age: ${ADMIN_AGE:0}
    gender: ${ADMIN_GENDER:male}
  # Base URL để runner upload gọi tới, mặc định tự build từ server.port + context-path
  upload:
    base-url: ${UPLOAD_BASE_URL:http://localhost:8000/api/v1}
